### ISSUE TITLE
Building out the Federal Front Door microsite

### ISSUE THREAD

**Issue by juliasolorzano** [18F/ffd-microsite#1]
This issue is for creating the initial build of the FFD Microsite. The specs and design layouts for this work are located in the Trello card link below.

**Trello card**
https://trello.com/c/TmesRUh0/9-as-a-government-employee-designing-services-that-interact-with-the-public-i-want-to-stay-up-to-date-with-the-research-findings-a

//cc @maya @rogeruiz

**Comment by rogeruiz** [comment]
Here's @maya checklist from #5 to keep it tracked in this issue. 

From @juliaelman: Adding final issue for testing plan for microsite
- [x] Add reports for download buttons
  - [x] Add custom analytics reporting for button clicks
- [x] Add meta info
- [x] Add sticky nav
  - [x] Add scrollyspy-like behavior (`$color-primary` for the active link)
- [x] perform testing https://github.com/18F/ffd-microsite/issues/16
- [x] check different widths and heights for the hero banner background image with heading text overlaid and adjust with media query ratios.

**Comment by juliasolorzano** [comment]
Done! :rocket: :us:
