### ISSUE TITLE
Point microsite to labs.usa.gov

### ISSUE THREAD

**Issue by juliasolorzano** [18F/ffd-microsite#10]
- [x] Work out who owns the zone and where it is/should be hosted
- [x] If the answer to the above does not involve 18F, we need to get host records added for the various microsite environments
- [x] Get SSL cert
- [x] [Set up an ELB with the SSL cert](https://docs.cloud.gov/ops/elb/)
- [x] [Have Cloud.gov support add the ELB to BOSH](https://github.com/18f/devops/issues/new)
- [x] Deploy microsite app with correct routing

**Comment by yozlet** [comment]
Added checklist to issue description.

**Comment by juliasolorzano** [comment]
Thanks @yozlet! ^5

**Comment by yozlet** [comment]
Created ELB, filed DevOps ticket, asked Russell (our usa.gov contact) to get the CNAME added.

**Comment by yozlet** [comment]
DevOps issue is: https://github.com/18F/DevOps/issues/567

**Comment by yozlet** [comment]
CNAME has now been added, and is pointing to the ELB.

**Comment by yozlet** [comment]
Added `labs.usa.gov` route to the `ffd-microsite` app in the `microsite-production` space.

**Comment by yozlet** [comment]
All done, we're live!
