### ISSUE TITLE
Perform testing plan on microsite

### ISSUE THREAD

**Issue by juliasolorzano** [18F/ffd-microsite#16]
This is a subset of checks for us to perform prior to launch:
- [x] Accessibility test (run HTML Codesniffer) and get :white_check_mark: from Nick Bristow
- [x] Browser testing
  - [x] lnternet Explorer 9 and up
  - [x] latest versions of Chrome, Firefox, and Safari
- [x] Mobile and responsive testing
  - [x] Resize your screen to make sure page elements resize appropriately
  - [x] Test on actual devices (iOS, Android, Windows)

**Comment by rogeruiz** [comment]
`Test in browsers...` and `Mobile and responsive testing` can probably be done using Saucelabs or Browserstack @juliaelman

**Comment by maya** [comment]
See: https://docs.google.com/document/d/1D-woKcLvydwhaEVgQ96nDVle1TF10NMc_fTPNVK6NP8/edit

**Comment by juliasolorzano** [comment]
@rogeruiz :+1: agreed, but do we have enough time to set this up and complete the testing by Friday?

**Comment by juliasolorzano** [comment]
@maya the link you posted is for a style guide talk? Is there somewhere in that talk that we should look at in regards to the testing plan?

**Comment by rogeruiz** [comment]
Right @juliaelman That makes sense. I will look at browsers today using
- VM for Windows Browsers
- Simulators for Android, iOS _any help testing on actual devices would be appreciated_
- Locally for Mac Browsers
- Locally on iPhone and iPad Mini/Pro

**Comment by juliasolorzano** [comment]
@rogeruiz awesome! I'll connect with you to see about divvying up the work too.

**Comment by juliasolorzano** [comment]
:+1: from @nickbristow

Tested with HTML Codesniffer too.

**Comment by nickbristow** [comment]
🙌

**Comment by juliasolorzano** [comment]
Testing is completed. Thanks team for knocking this one out so quickly!

![mind_blown](https://cloud.githubusercontent.com/assets/955558/13358415/34c29758-dc7d-11e5-93ab-c56d9b1570ec.gif)
